### ISSUE TITLE
Som kund vill jag kunna hitta information om företaget i Footern

### ISSUE THREAD

**Issue by Rebuuz** [Rika-group-7/Rika-webapp#155]
## Beskrivning:
I footern ska en länk ligga till sidan /AboutUs

## Tasks:
- [ ] Skapa en länk i footern som leder till /AboutUs
- [ ] I /AboutUs lägg till diverse länkar som /WhyUs och /OurMission

## Acceptanskriterier: 
- [ ] Användaren ska kunna klicka på /AboutUs
- [ ] /AboutUs ska vara populerad med diverse länkar så som /WhyUs och /OurMission

## Testbeskrivning: 
- [ ] Testa så att länken tar en till sidan /AboutUs
