### ISSUE TITLE
Som besökare vill jag kunna hitta karriärer i Footern

### ISSUE THREAD

**Issue by Rebuuz** [Rika-group-7/Rika-webapp#156]
## Beskrivning:
I footern ska en länk ligga till sidan /Careers eller /WorkWithUs

## Tasks:
- [ ] Skapa en länk i footern som leder till /Careers
- [ ] I /Careers lägg till relevanta länkar till samtliga lediga tjänster 

## Acceptanskriterier: 
- [ ] Användaren ska kunna klicka på /Careers
- [ ] /Careers ska vara populerad med diverse länkar så som /LeadigaTjeanster etc

## Testbeskrivning: 
- [ ] Testa så att länken tar en till sidan /Careers
- [ ] Testa så att till exempel länken lediga tjänster tar en till /LeadigaTjeanster
