### ISSUE TITLE
Som besökare vill jag kunna hitta information om Privacy Policy i Footern

### ISSUE THREAD

**Issue by Rebuuz** [Rika-group-7/Rika-webapp#157]
## Beskrivning:
I footern ska en länk ligga till sidan /Policies

## Tasks:
- [ ] Skapa en länk i footern som leder till /Policies
- [ ] I /Policies skapa en länk till /PrivacyPolicy

## Acceptanskriterier: 
- [ ] Användaren ska kunna klicka på /Policies
- [ ] /Policies ska vara populerad med diverse länkar så som /PrivacyPolicy

## Testbeskrivning: 
- [ ] Testa så att länken tar en till sidan /Policies
- [ ] Testa så att privacy policy länken tar en till /PrivacyPolicy
