### ISSUE TITLE
Som användare vill jag kunna se min profilinformation

### ISSUE THREAD

**Issue by fianchetto3** [Rika-group-7/Rika-webapp#74]
### Task
- [ ] #168
- [ ] #169
- [ ] #82 
- [ ] #75 

### Acceptanskritierer
- [ ]  Användarens profilinformation ska hämtas när användaren går in på profilsidan.
- [ ]  Användarens information ska inkludera: Namn, Efternamn, Epost, profilbild och kön.
- [ ]  Om användarens data inte laddar in ska ett felmeddelande visas.

### Testbeskrivning
 Testfall för att säkerställa att profilinformationen laddas in korrekt och att felhantering fungerar

**Ladda och visa profilinformation** 
 - [ ] Efterlikna ett API-repsons med användarens fullständiga information
 - [ ] Kontrollera att variablerna stämmer överens med vad som ska finnas på profilsidan

**Felhantering vid misslyckat API-anrop**    
  - [ ] Steg 1 Skapa ett API-anrop som simulerar ett misslyckat fall av att hämta användarens data.
  - [ ] Steg 2 Öppna profilsidan för att kontrollera att ett felmeddelande syns

Förväntat resultat är att användarinformationen ska laddas in korrekt och att det ska finnas felhantering ifall något misslyckas vid hämtningen.
